### ISSUE TITLE
Ability to hide line numbers

### ISSUE THREAD

**Issue by vitalybaev** [speed-highlight/core#22]
Sometimes we don't want to display line numbers.

**Describe the solution you'd like**
It seems that we should add another optional argument to `highlightElement`. It should be an object with parameters (more settings can be tweaked here in the future).

**Describe alternatives you've considered**
We don't have some solution with this package.

**Additional context**
I can create a PR with this feature. I only want to hear your approval.

**Comment by matubu** [comment]
this is great idea,
you can create a PR with this feature but try to keep the size as small as possible,
thanks,
Mathias
