### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by transitive-bullshit** [speed-highlight/core#25]
Just came across this project and it looks really, really awesome!

I wanted to provide some constructive feedback and ask some questions that might help.

#### Suggestions

- demo url is missing from the github repo settings (I usually skim new projects and this is one of the most important signals I look for)
- demo should use more common defaults; asm => typescript or javascript; atom-dark => default or dark; disable line numbering by default
- the API seems like it may be a drop-in replacement for prismjs which is awesome, but I don't see this mentioned anywhere. maybe add a "migrating from prism" section or a comparisons section w/ notes about other options?
- the demo styling could use some love; on wide screens maybe set the content max-width to be centered at 1000px or something
- would love to see a section on how to use w/ react, vue, etc. happy to contribute a minimal react demo or a react npm package wrapper it it helps

#### Questions

- are there other planned packages outside of `speed-highlight/core`?
```const { setTheme, printHighlight } = require('@speed-highlight/core/dist/node/term.js');```
- what is term? any chance you could make this import a little more clean?

Note: I don't usually provide this level of feedback, but I really like what you've built (I've been struggling w/ prismjs recently), and I see it having the potential to become widely used.

**Comment by matubu** [comment]
Hello,
Thanks for this amazing feedback, I tried to take all of your suggestions.
I did not create a demo or package for frameworks but you can give it a try if you want.
For the moment there is no package planned outside of speed-highlight/core
And term (now terminal) is an adaptor that allows you to print in the terminal with syntax highlighting on a node or a deno server

Thanks, Mathias
