### ISSUE TITLE
[BUG] Syntax Highlighting Glitch of Camel-Case code in Java

### ISSUE THREAD

**Issue by inpa-dev** [speed-highlight/core#30]
**Information**
  * Speed-highlight.js version : 1.1.7
  * Browser version : Chrome 109.0.5414.75

**Description**
I real like this project but, It has a problem about Syntax Highlighting of Camel-Case of variables in Java Language; solve plz...
![image](https://user-images.githubusercontent.com/46434555/218445068-a0ed03e2-4364-48a2-8a0d-1cf2d6ad5def.png)

**Example**
https://codepen.io/inpaSkyrim/pen/zYJOpLJ

**Comment by matubu** [comment]
Hi,
Thanks for the report, it should be fixed now,
Have a good day
