### ISSUE TITLE
[FEATURE] Add typescript definitions

### ISSUE THREAD

**Issue by BearToCode** [speed-highlight/core#32]
Hello, first of all I want to thank you for this awesome library!
My request is pretty simple: add typings definitions so that all typescript users can enjoy this library as well!

**Comment by matubu** [comment]
Thanks for the request! I appreciate your kind words. Adding TypeScript typings is a good idea, but unfortunately, I don't have the time to work on it at the moment. However, you can consider contributing to the project or maybe someone else from the community could take it up.
