### ISSUE TITLE
[BUG]: CSS files return `404`

### ISSUE THREAD

**Issue by gutenfries** [speed-highlight/core#37]
## Description

CSS files from `/src/themes/*` are not making it to `dist/themes/*` for one reason or another. 

If this is a breaking change in the API, i.e., this is intentional, a major release and documentation of these changes for consumers is in order.

| unpkg screenshot: |
| --- |
| ![Screenshot from 2023-08-05 11-29-32](https://github.com/speed-highlight/core/assets/79616833/9294b5bf-5a3b-41dc-9356-e4e4f60d1e29) |

| My website, which uses speedhighlight (open console for error): |
| --- |
| https://gutenfries.deno.dev/blog/create-a-css-drum-animation |

**Comment by matubu** [comment]
I sincerely apologize for the inconvenience you experienced. The issue has been resolved now. It was caused by a recent GitHub PR that introduced changes to the build system.

Thank you for your patience and understanding.

Mathias
