### ISSUE TITLE
[BUG] [class*=shj-lang-] color & background defined twice in github-* themes

### ISSUE THREAD

**Issue by dflock** [speed-highlight/core#41]
**Information**
  * Speed-highlight.js version 1.2.6
  * Browser version n/a

**Description**

If we look at github-dark.css, for example, we see this at the top:

```css
[class*='shj-lang-'] {
    white-space: pre;
    margin: 10px 0;
    border-radius: 10px;
    padding: 30px 20px;
    background: #fff;
    color: #112;
...
```

and this further down:

```css
[class*='shj-lang-'] {
    color: #24292f;
    background: #fff;
}
```

This a bit redundant and also makes it slightly harder to update these styles, which is how I bumped into this.

**Expected behavior**
Just define the color & background once.

I just wanted to add that this project is awesome! Super lightweight and fast - the best lightweight highlighting library 0 thanks!

**Comment by matubu** [comment]
It's because there is a base style in `default.css` that is imported in every other style sheets, and then only the colors are changed. I thought the minifier would merge rules. I will look into that
