### ISSUE TITLE
[BUG] XML syntax highlighting skips namespaced elements and attributes

### ISSUE THREAD

**Issue by vincentml** [speed-highlight/core#49]
**Information**
  * Speed-highlight.js version: CDN 1.2.6
  * Browser version: Chrome 131.0.6778.109, Vivaldi 7.0.3495.23 (Stable channel) (64-bit) 

**Description**
The XML syntax highlighting is skipping elements and attributes that use a namespace prefix, and is skipping processing instructions. While trying to diagnose this problem, I see that in src/languages/xml.js:

1. the regular expression pattern in "property" does not include the colon (:) character. [Line 1](https://github.com/speed-highlight/core/blob/11aeddf0622f3a2f7bb5093748504dfcdb62d1df/src/languages/xml.js#L1)

2. the regular expression for processing instructions ignores processing instructions that do not begin with the letters "xml". [Line 43](https://github.com/speed-highlight/core/blob/11aeddf0622f3a2f7bb5093748504dfcdb62d1df/src/languages/xml.js#L43)

**Example**

Here is an XML document containing a few examples of elements and attributes and a processing instruction that are currently being skipped and not syntax highlighted:

```xml
<article xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:oasis="http://www.niso.org/standards/z39-96/ns/oasis-exchange/table" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:ali="http://www.niso.org/schemas/ali/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" article-type="research-article" xml:lang="en" dtd-version="1.2">
    
    <inline-graphic xlink:href="filename.png"/>
    
    <mml:math>
        <mml:mn>4</mml:mn>
        <mml:mo>&#x2264;</mml:mo>
        <mml:mi>x</mml:mi>
        <mml:mo>&lt;</mml:mo>
        <mml:mn>10</mml:mn>
        <mml:mrow>
            <mml:mtext>"&#xA0;</mml:mtext>
        </mml:mrow>
    </mml:math>
    
    <?processing-instruction-name processing-instruction-value?>
    
    <p content-type="example">This element and attribute is here to show that speed-highlight is running.</p>
    
</article>
```

Screenshot showing that speed-highlight running but is skipping over elements and attributes that contain a colon and skipping over processing instructions.

![image](https://github.com/user-attachments/assets/468837fd-7c59-4fd3-ac0f-7f7f3827b055)

**Expected behavior**

Elements and attributes that have a namespace and processing instructions should be syntax highlighted. Here is an example from another program (oXygen XML Editor):

![image](https://github.com/user-attachments/assets/0e167c27-3a17-41f9-bb99-f370e40a3361)

**Additional Information**

In case this is helpful, the formal syntax for XML has more extensive sets of character patterns that are allowed. The [W3C XML Recommendation](https://www.w3.org/TR/REC-xml/) is a good reference for this, and there is a concise [grammar file showing the formal syntax for XML here](https://github.com/GuntherRademacher/rex-parser-generator/blob/main/docs/sample-grammars/XML.ebnf)

**Comment by vincentml** [comment]
I've created a pull request PR #50 to address this issue.

**Comment by vincentml** [comment]
@matubu Thanks for merging my pull request!

I see you've made further improvements, which are helpful to see to better understand how speed-highlight works.

There is a difference in how processing instructions are being highlighted now in "main" compared to the pull request. Here are a few examples of various processing instructions:

```xml
<?processing-instruction-name processing instruction value?>
<?pi-name att="value" att2="value2"?>
<?pi-name att="value" att2="value2" text ?>
```

In this screenshot based on the current "main" branch, individual words in the processing instruction value (the example that doesn't contain attribute="value" pairs) are matched as "class". This is inconsistent with how highlighting is applied to XML elements where "class" is used to highlight attribute names and "str" is used to highlight values.

![image](https://github.com/user-attachments/assets/08957091-e763-41b8-907e-0d799d6fba19)


In this screenshot based on my version the entire value of the processing instruction is matched as "str", except if there are attribute="value" or attribute='value' pairs in which case the attribute name is matched as "class", the "=" is matched as "oper", and the value including quotes is matched as "str". 

![image](https://github.com/user-attachments/assets/9ba45d91-ff96-4fd1-81e3-cb6eb9165c3b)

Inspecting the source shows:

![image](https://github.com/user-attachments/assets/b5a52000-c375-4d14-8b1a-2ae519a84bf2)
![image](https://github.com/user-attachments/assets/4e1ad8df-02f1-4daa-b39f-112541e6b188)

**Comment by matubu** [comment]
Yeah, I've done it on purpose. I thought it was more coherent to use the same color for the attribute name all the time. It seems like GitHub does it this way too. I don't totally understand why you think it would be more coherent to use a different color. Aren't `processing instruction value` multiple attribute names, like `required` is an attribute name in `<input required />` in HTML?


![image](https://github.com/user-attachments/assets/0054cef9-3c2d-46ee-98fc-9df664d3aeba)

**Comment by vincentml** [comment]
The syntax for processing instructions is not really like the HTML syntax `<input required />`. Based on the example in your comment, the syntax highlighting that GitHub does for processing instructions is inaccurate. Several other syntax highlighters that I've seen do not handle XML processing instructions very well.

The formal grammar for XML defines the pattern for a processing instruction as follows. (The EBNF syntax is different than regular expression syntax but has some similarities.)

```ebnf
PI       ::= '<?' PITarget ( S ( [^?] | '?'+ [^?>] )* '?'* )? '?>'
PITarget ::= Name
```

Here's a minimal example of a PI with just a name:

* `<?name?>`
  * `<?` = start sequence, type "oper"
  * `name`  = name of the processing instruction, type "var"
  * `?>` =  end sequence, type "oper"

A PI can optionally have a space and a value after the name. Everything that follows the space after the name up to the final `?>` is technically the value of the processing instruction. Here's an example of a PI with a name and a value. 

* `<?name any text except the end sequence?>`
  * `<?` = start sequence, type "oper"
  * `name`  = name of the processing instruction, type "var"
  * ` ` = space character
  * `any text except the end sequence` = value of the processing instruction, type "str"
  * `?>` =  end sequence, type "oper"

Except for the special `<?xml?>` processing instruction, XML parsers see the value in a processing instruction as technically just a text string. However, it is common for the value to be formatted as attributes so that parsable data can be stored in a processing instruction. Here's an example of a PI whose value is an attribute with a value. 

* `<?name attributeName="attributeValue"?>`
  * `<?` = start sequence, type "oper"
  * `name`  = name of the processing instruction, type "var"
  * ` ` = space character
  * `attributeName` = attribute name, type "class"
  * `=` = equals, type "oper"
  * `"attributeValue"` = attribute value, type "str" (side note: the quotes are not part of the attribute value but it's ok for syntax highlighting)
  * `?>` =  end sequence, type "oper"

To match the way XML elements are syntax highlighted, if my understanding is correct:

* "var" should be assigned to the PI name 
* "str" should be assigned to the value of the processing instruction and to attribute values
* "class" should be assigned to attribute names
* "oper" should be assigned to `<?`, `?>`, and `=`

Does this explanation make sense?

**Comment by matubu** [comment]
Ok, that makes sense. I've tried to find a middle ground because any data can be in between, but it seems to be almost always classical properties. So I consider them as properties, and if they are invalid, they are highlighted as a string.

**Comment by vincentml** [comment]
I've just tried using the new release. Syntax highlighting for processing instructions looks good. Thank you for adding these changes and releasing an update so quickly!
